# Generated by Django 5.1.3 on 2024-11-18 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveSmallIntegerField(error_messages={'max_value': 'Максимальное?', 'min_value': 'Минимальное?'}, validators=[django.core.validators.MinValueValidator(1, message='Минимальное?'), django.core.validators.MaxValueValidator(5, message='Максимальное?')]),
        ),
    ]
