auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  wal:
    enabled: false
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
