name: Python CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install pylint
      - name: Run linter
        run: pylint python/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest python/ --junitxml=report.xml
      - name: Save test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml
