name: CI with SonarQube and pylint

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint and generate report
        run: |
          pylint your_project_directory --output-format=json > pylint-report.json

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ReznikovRoman_itmo-devops-masters-course
            -Dsonar.python.pylint.reportPaths=pylint-report.json
